config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :posts
  resources :users
  resources :users

  root 'mondo#index'

  namespace :mondo do
    get "frontend"
    get "backend"
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mondo_controller.rb
class MondoController < ApplicationController

	before_action :authenticate_admin!, only: [:backend]

	def frontend
		redirect_to :root
	end

	def backend

	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @users = User.all
  end

  # GET /posts/1/edit
  def edit
    @users = User.all
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width" />
  <title>MondoLabsTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="collapse navbar-collapse" id="nav-menu-collapse">
   	<ul class="nav navbar-nav">
			<div class="container">
				<li class="nav"><%= link_to('Home', root_path, class: "nav") %></li>
				<% if admin_signed_in? %>
					<li class="nav"><%= link_to('Sign Out', destroy_admin_session_path, method: :delete, class: "nav") %></li>
				<% else %>
					<li class="nav"><%= link_to('Sign In', new_admin_session_path, class: "nav") %></li>
					<li class="nav"><%= link_to('Sign Up', new_admin_registration_path, class: "nav") %></li>
				<% end %>
				<li class="nav">
					<a class="nav" href="/mondo/backend">CMS</a>
				</li>
			</div>	
    </ul>
  </div>
	<div class="container">
		<nav class="navbar navbar-default">
	    <div class="navbar-header">
	      <button type="button" class="navbar-trigger">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar first"></span>
	        <span class="icon-bar second"></span>
	        <span class="icon-bar third"></span>
	      </button>
	      <a class="navbar-brand" href="/">
	      	<%= image_tag("selus-logo.png", alt: "Selus Logo", class: "nav-logo")%><span class="logo-text">Selus</span>
	      </a>
	    </div>
		</nav>
	</div>	

	<p class="notice">
		<%= notice %>
	</p>
	<p class="alert">
		<%= alert %>
	</p>

<%= yield %>

</body>
</html>

app/views/mondo/_cd_svg.html.erb
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="47px" height="47px" viewBox="0 0 47 47" enable-background="new 0 0 47 47" xml:space="preserve">
<path fill="#EF3B3A" d="M23.5,0C10.522,0,0,10.521,0,23.5C0,36.479,10.522,47,23.5,47S47,36.479,47,23.5C47,10.521,36.478,0,23.5,0z
	 M13.5,7.267l5.053,10.838c-0.156,0.144-0.306,0.292-0.449,0.449L7.266,13.499C8.833,10.967,10.967,8.831,13.5,7.267z M23.5,26.438
	c-1.621,0-2.938-1.318-2.938-2.938s1.316-2.938,2.938-2.938c1.621,0,2.938,1.318,2.938,2.938S25.121,26.438,23.5,26.438z
	 M23.5,42.594c-10.528,0-19.094-8.566-19.094-19.094c0-2.103,0.355-4.121,0.985-6.014l10.86,5.064
	c-0.042,0.314-0.096,0.624-0.096,0.95c0,4.056,3.287,7.344,7.344,7.344c0.324,0,0.634-0.054,0.948-0.096l5.064,10.861
	C27.619,42.24,25.603,42.594,23.5,42.594z M33.5,39.735l-5.055-10.839c0.158-0.143,0.307-0.292,0.45-0.45L39.733,33.5
	C38.169,36.034,36.033,38.169,33.5,39.735z M30.749,24.447c0.04-0.312,0.095-0.622,0.095-0.946c0-4.056-3.288-7.344-7.344-7.344
	c-0.324,0-0.636,0.055-0.95,0.096L17.486,5.392c1.893-0.631,3.912-0.986,6.014-0.986c10.528,0,19.094,8.566,19.094,19.094
	c0,2.102-0.354,4.119-0.984,6.013L30.749,24.447z"/>
</svg>

app/views/mondo/_download.html.erb
<div class="container download">
	<div class="title__outer--wrapper download">
		<div class="title__wrapper download">
			<div class="title__inner--wrapper download">
				<h2 class="title-text">Discover new music &amp; stuff</h2>
			</div>
			<p class="body-text download">
				Consectetur adipiscing elit. Ut fermentum condimentum massa, in sagittis dolor feugiat id. Morbi pharetra elit non lorem elementum iaculis. 
			</p>
			<div class="downloads__image--wrapper">
				<%= image_tag('download-phones.png', class: 'download-phones')%>
			</div>
			<div class="button__wrapper title download">
				<button type="button" id="#downloadButton" class="button">
					Download the app
				</button>
			</div>
		</div>
	</div>
</div>

app/views/mondo/_features.html.erb
<div class="features__wrapper">
	<div class="features__header--wrapper">
		<h2 class="text__align--center title-text"><span class="text__align--center blue">Selus</span> with lots of features</h2>
	</div>
	<div class="features__inner--wrapper">
		<div class="mobile features-phone__image--wrapper">
			<%= image_tag('features-phone-image.png', class: "features-phone")%>
			<div class="features-phone-shadow__wrapper relative-z-1">
				<%= image_tag('features-phone-shadow.png', class: "relative-z-1 features-phone-shadow")%>
			</div>
		</div>
		<div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 col-xs-12 relative-z-1">
			<div class="feature__wrapper">
				<%= render partial: 'speaker_svg' %>
				<h3 class="feature">
					Lorem ipsum dolor sit amet
				</h3>
				<p class="body-text">
					Consectetur adipiscing elit. Ut fermentum condimentum massa, in sagittis dolor feugiat id. Morbi pharetra elit non lorem elementum iaculis.
				</p>
			</div>
			<div class="feature__wrapper">
				<%= render partial: 'activity_svg' %>
				<h3 class="feature">
					Lorem ipsum dolor sit amet
				</h3>
				<p class="body-text">
					Consectetur adipiscing elit. Ut fermentum condimentum massa, in sagittis dolor feugiat id. Morbi pharetra elit non lorem elementum iaculis.
				</p>			
			</div>
		</div>
		<div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 hidden-mobile features-phone__image--wrapper">
			<%= image_tag('features-phone-image.png', class: "features-phone")%>
			<div class="features-phone-shadow__wrapper relative-z-1">
				<%= image_tag('features-phone-shadow.png', class: "relative-z-1 features-phone-shadow")%>
			</div>
		</div>
		<div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 col-xs-12 relative-z-1">
			<div class="feature__wrapper">
				<%= render partial: 'headphones_svg' %>
				<h3 class="feature">
					Lorem ipsum dolor sit amet
				</h3>
				<p class="body-text">
					Consectetur adipiscing elit. Ut fermentum condimentum massa, in sagittis dolor feugiat id. Morbi pharetra elit non lorem elementum iaculis.
				</p>		
			</div>
			<div class="feature__wrapper">
				<%= render partial: 'cd_svg' %>
				<h3 class="feature">
					Lorem ipsum dolor sit amet
				</h3>
				<p class="body-text">
					Consectetur adipiscing elit. Ut fermentum condimentum massa, in sagittis dolor feugiat id. Morbi pharetra elit non lorem elementum iaculis.
				</p>
			</div>
		</div>
	</div>
</div>

app/views/mondo/_footer.html.erb
<hr class="footer">
<div class="footer__text--wrapper">
	<ul class="left">
		<li class="footer-blue">
			<a href="#">
				Homepage
			</a>
		</li>
		<li class="footer-blue">
			<a href="#">
				Services
			</a>
		</li>
		<li class="footer-blue">
			<a href="#">
				About us
			</a>
		</li>
		<li class="footer-blue">
			<a href="#">
				Contact
			</a>
		</li>
	</ul>
	<span class="right">
		<p class="footer-blue">
			Copyright ⓒ 2015. All rights reserved by Selus
		</p>
	</span>
</div>	

app/views/mondo/_headphones.html.erb
<div class="headphones__wrapper">
	<div class="headphones__image-wrapper">
		<%= image_tag('headphones-image.png', class: "headphones")%>
	</div>	
	<div class="headphones__container">
		<h2 class="title-text text__align--center"><span class="text__align--center  blue">Selus</span> is for music</h2>
		<p class="headphones body-text">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fermentum condimentum massa, in sagittis dolor feugiat id. Morbi pharetra elit non lorem elementum iaculis. Curabitur aliquet lacus sit amet metus molestie ultrices vel in nibh. Sed sit amet feugiat turpis, ut bibendum velit. In et felis mauris.
		</p>
		<div class="button__wrapper headphones">
			<button type="button" id="#headphonesButton" class="button">
				View more
			</button>
		</div>
	</div>
</div>

app/views/mondo/_headphones_svg.html.erb
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="55px" height="52px" viewBox="0 0 55 52" enable-background="new 0 0 55 52" xml:space="preserve">
<path fill="#EF3B3A" d="M50.638,31.667c0.725-2.304,1.126-4.75,1.126-7.292C51.765,10.935,40.88,0,27.5,0
	C14.12,0,3.235,10.935,3.235,24.375c0,2.542,0.401,4.988,1.126,7.292C1.711,33.749,0,36.984,0,40.626C0,46.908,5.069,52,11.323,52
	h1.618c1.787,0,3.235-1.455,3.235-3.25V32.5c0-1.795-1.449-3.25-3.235-3.25h-1.618c-0.867,0-1.708,0.106-2.52,0.292
	c-0.453-1.648-0.716-3.375-0.716-5.167c0-10.752,8.708-19.5,19.412-19.5c10.704,0,19.412,8.748,19.412,19.5
	c0,1.792-0.262,3.518-0.716,5.167c-0.812-0.185-1.652-0.292-2.52-0.292h-1.618c-1.787,0-3.235,1.455-3.235,3.25v16.25
	c0,1.795,1.449,3.25,3.235,3.25h1.618C49.931,52,55,46.908,55,40.626C55,36.984,53.289,33.749,50.638,31.667z M11.323,47.126
	c-3.568,0-6.471-2.916-6.471-6.5c0-3.585,2.902-6.5,6.471-6.5V47.126z M43.676,47.126v-13c3.569,0,6.471,2.916,6.471,6.5
	C50.147,44.21,47.245,47.126,43.676,47.126z"/>
</svg>

app/views/mondo/_opinions.html.erb
<div class="opinions__wrapper">
	<div class="opinions__bg-image--wrapper">
		<div class="opinions">

			<div>
			  <div class="opinions__text--outer-wrapper">
			  	<div class="opinions__text--inner-wrapper">
						<div class="opinions__text--wrapper">
					  	<p class="opinions-text">
					  		Consectetur adipiscing elit. Ut fermentum condimentum massa, in sagittis dolor feugiat id. Morbi pharetra elit non lorem elementum iaculis. 
					  	</p>
					  	<div class="avatar__wrapper">
					  		<span class="body-text">
					  			<%= image_tag('opinion-face-1.png', class: 'opinion-face')%>
				  				Patrick Wasik, 
					  			<span class="tiny-blue">
					  				Graphic Designer at SYMU
					  			</span>
					  		</span>
					  	</div>
						</div>
					</div>	
			  </div>
			</div>

			<div>
			  <div class="opinions__text--outer-wrapper">
			  	<div class="opinions__text--inner-wrapper">
						<div class="opinions__text--wrapper">
					  	<p class="opinions-text">
					  		2 Consectetur adipiscing elit. Ut fermentum condimentum massa, in sagittis dolor feugiat id. Morbi pharetra elit non lorem elementum iaculis. 
					  	</p>
					  	<div class="avatar__wrapper">
					  		<span class="body-text">
					  			<%= image_tag('opinion-face-2.png', class: 'opinion-face')%>
				  				Patrick Wasik, 
					  			<span class="tiny-blue">
					  				Graphic Designer at SYMU
					  			</span>
					  		</span>
					  	</div>
						</div>
					</div>	
			  </div>
			</div>

			<div>
			  <div class="opinions__text--outer-wrapper">
			  	<div class="opinions__text--inner-wrapper">
						<div class="opinions__text--wrapper">
					  	<p class="opinions-text">
					  		3 Consectetur adipiscing elit. Ut fermentum condimentum massa, in sagittis dolor feugiat id. Morbi pharetra elit non lorem elementum iaculis. 
					  	</p>
					  	<div class="avatar__wrapper">
					  		<span class="body-text">
					  			<%= image_tag('opinion-face-1.png', class: 'opinion-face')%>
				  				Patrick Wasik, 
					  			<span class="tiny-blue">
					  				Graphic Designer at SYMU
					  			</span>
					  		</span>
					  	</div>
						</div>
					</div>	
			  </div>
			</div>

			<div>
			  <div class="opinions__text--outer-wrapper">
			  	<div class="opinions__text--inner-wrapper">
						<div class="opinions__text--wrapper">
					  	<p class="opinions-text">
					  		4 Consectetur adipiscing elit. Ut fermentum condimentum massa, in sagittis dolor feugiat id. Morbi pharetra elit non lorem elementum iaculis. 
					  	</p>
					  	<div class="avatar__wrapper">
					  		<span class="body-text">
					  			<%= image_tag('opinion-face-2.png', class: 'opinion-face')%>
				  				Patrick Wasik, 
					  			<span class="tiny-blue">
					  				Graphic Designer at SYMU
					  			</span>
					  		</span>
					  	</div>
						</div>
					</div>	
			  </div>
			</div>

			<div>
			  <div class="opinions__text--outer-wrapper">
			  	<div class="opinions__text--inner-wrapper">
						<div class="opinions__text--wrapper">
					  	<p class="opinions-text">
					  		5 Consectetur adipiscing elit. Ut fermentum condimentum massa, in sagittis dolor feugiat id. Morbi pharetra elit non lorem elementum iaculis. 
					  	</p>
					  	<div class="avatar__wrapper">
					  		<span class="body-text">
					  			<%= image_tag('opinion-face-1.png', class: 'opinion-face')%>
				  				Patrick Wasik, 
					  			<span class="tiny-blue">
					  				Graphic Designer at SYMU
					  			</span>
					  		</span>
					  	</div>
						</div>
					</div>	
			  </div>
			</div>


		</div>
		<span id="dotsWrrapper">
		</span>
	</div>
</div>

app/views/mondo/_perspective.html.erb
<div class="perspective__wrapper">
	<div class="perspective__container">
		<h3 class="title-text">Lorem ipsum dolor sit amet</h2>
		<p class="perspective body-text">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fermentum condimentum massa, in sagittis dolor feugiat id. Morbi pharetra elit non lorem elementum iaculis. Curabitur aliquet lacus sit amet metus molestie ultrices vel in nibh. Sed sit amet feugiat turpis, ut bibendum velit. In et felis mauris.
		</p>
	</div>
	<div class="perspective__image-wrapper">
		<%= image_tag('perspective-image.png', class: "perspective")%>
	</div>
</div>

app/views/mondo/_power-button.html.erb
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="50px" height="51px" viewBox="0 0 50 51" enable-background="new 0 0 50 51" xml:space="preserve">
<path fill-rule="evenodd" clip-rule="evenodd" fill="#EF3B3A" d="M25,51C11.215,51,0,39.918,0,26.297
	C0,18.216,4.035,10.63,10.796,6.003c0.398-0.272,0.851-0.409,1.302-0.422c0.792-0.025,1.58,0.336,2.063,1.025
	c0.761,1.086,0.487,2.576-0.611,3.328c-5.456,3.734-8.712,9.851-8.712,16.363c0,10.985,9.044,19.922,20.161,19.922
	c11.117,0,20.161-8.937,20.161-19.922c0-6.512-3.256-12.629-8.712-16.363c-1.099-0.751-1.372-2.241-0.611-3.328
	C36.312,5.93,37.08,5.57,37.857,5.58c0.466,0.004,0.936,0.141,1.347,0.423C45.964,10.63,50,18.216,50,26.297
	C50,39.918,38.785,51,25,51z M25,19.125c-1.336,0-2.419-1.071-2.419-2.39V2.391C22.581,1.07,23.664,0,25,0s2.419,1.07,2.419,2.391
	v14.344C27.419,18.054,26.336,19.125,25,19.125z"/>
</svg>

app/views/mondo/_title.html.erb
<div class="container">
	<div class="title__outer--wrapper">
		<div class="title__wrapper">
			<div class="title__inner--wrapper">
				<h2 class="title-text"><span class="blue">Selus</span> is cool app</h2>
			</div>
			<div class="button__wrapper title">
				<button type="button" id="#titleButton" class="button">
					Explore
				</button>
			</div>
		</div>
	</div>
</div>

app/views/mondo/backend.html.erb
<div class="cms__wrapper">
	<h1 class="white text-aligned__center">
		CMS
	</h1>
	<div class="container">
		<div class="cms__links--outer-wrapper">
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<%= link_to ('<i class="big-icon fa fa-user" aria-hidden="true"></i><br><h2 class="cms__link text-aligned__center">Users</h2>').html_safe, users_path, class: "cms__link" %>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<%= link_to ('<i class="big-icon fa fa-file-text-o" aria-hidden="true"></i><br><h2 class="cms__link text-aligned__center">Posts</h2>').html_safe, posts_path, class: "cms__link"%>
			</div>
	</div>
</div>	

app/views/mondo/frontend.html.erb
front

app/views/posts/edit.html.erb
<h2 class="center">Edit Post</h2>


<%= render 'form' %>

<div class="container">
	<%= link_to 'Show', @post %> |
	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <!-- <p id="notice"><%= notice %></p> -->
  <h2 class="center">Posts</h2>
  <table class="mondo posts">
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.content %></td>
          <td><%= post.user.username %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Post', new_post_path %>
  <br>
  <%= link_to 'CMS', mondo_backend_path %>
</div>

app/views/posts/new.html.erb
<h2 class="center">New Post</h2>

<%= render 'form' %>

<div class="container">
	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container margin__top--40">
	
	<p class="blue">
	  Title:
	</p>
	 
	<h4 class="white">
		<%= @post.title %>
	</h4>
	<hr class="cms">
	<br>

	<p class="blue">
	  User:
	</p>
	 
	<h4 class="white">
  	<%= @post.user.username %>
	</h4>
	<hr class="cms">
	<br>

	<p class="blue">
	  Content:
	</p>
	 
	<h4 class="white">
	  <%= @post.content %>
	</h4>
	<hr class="cms">
	<br>

	<%= link_to 'Edit', edit_post_path(@post) %>
	<br>
	<%= link_to 'Back', posts_path %>
</div>	

app/views/users/edit.html.erb
<h2 class="center">Edit User</h2>

<%= render 'form' %>

<div class="container">
	<%= link_to 'Show', @user %><br>
	<%= link_to 'Back', users_path %>
</div>	

app/views/users/index.html.erb
<div class="container">
  <!-- <p id="notice"><%= notice %></p> -->
  <h2 class="center">Users</h2>
  <table class="mondo users">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Username</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.email %></td>
          <td><%= user.username %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New User', new_user_path %>
  <br>
  <%= link_to 'CMS', mondo_backend_path %>
</div>

app/views/users/new.html.erb
<h2 class="center">New User</h2>

<%= render 'form' %>

<div class="container">
	<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="container margin__top--40">
	
	<p class="blue">
	  First name:
	</p>
	 
	<h4 class="white">
		<%= @user.first_name %>
	</h4>
	<hr class="cms">
	<br>

	<p class="blue">
	  Last name:
	</p>
	 
	<h4 class="white">
	  <%= @user.last_name %>
	</h4>
	<hr class="cms">
	<br>

	<p class="blue">
	  Email:
	</p>
	 
	<h4 class="white">
	  <%= @user.email %>
	</h4>
	<hr class="cms">
	<br>

	<p class="blue">
	  Username:
	</p>
	 
	<h4 class="white">
	  <%= @user.username %>
	</h4>
	<hr class="cms">
	<br>

	<%= link_to 'Edit', edit_user_path(@user) %>
	<br>
	<%= link_to 'Back', users_path %>
</div>	